CREATE TABLE etl.diesel_report
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    estacion             VARCHAR(100),
    flota                VARCHAR(100),
    area                 VARCHAR(100),
    modelo               VARCHAR(100),
    dispositivo          VARCHAR(100),
    cantidad             INTEGER,
    producto             VARCHAR(100),
    fecha                date,
    interior_superficie  VARCHAR(50),
    familia              VARCHAR(100),
    colorada_contratista VARCHAR(100),
    mes                  VARCHAR(20),
    row_hash             VARCHAR(64)                             NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_diesel_report PRIMARY KEY (id)
);

ALTER TABLE etl.diesel_report
    ADD CONSTRAINT uk_diesel_report_row_hash UNIQUE (row_hash);