CREATE TABLE etl.salida_acero
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha             date                                    NOT NULL,
    turno             VARCHAR(20),
    grupo             VARCHAR(50),
    codigo            VARCHAR(100),
    acero             VARCHAR(100),
    cantidad          INTEGER,
    equipo_cod        VARCHAR(50),
    equipo            VARCHAR(100),
    nomina_operador   VARCHAR(50),
    operador          VARCHAR(150),
    nomina_supervisor VARCHAR(50),
    supervisor        VARCHAR(150),
    zona              VARCHAR(100),
    proveedor         VARCHAR(150),
    costo             DECIMAL(14, 2),
    row_hash          VARCHAR(64)                             NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_salida_acero PRIMARY KEY (id)
);

ALTER TABLE etl.salida_acero
    ADD CONSTRAINT uk_salida_acero_row_hash UNIQUE (row_hash);

CREATE INDEX ux_salida_acero_row_hash ON etl.salida_acero (row_hash);