CREATE TABLE etl.diesel_budget
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipo      VARCHAR(100)                            NOT NULL,
    descripcion VARCHAR(200),
    familia     VARCHAR(100),
    lts_hra     DECIMAL(20, 10),
    mes         INTEGER                                 NOT NULL,
    anio        INTEGER                                 NOT NULL,
    row_hash    VARCHAR(64)                             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_diesel_budget PRIMARY KEY (id)
);

ALTER TABLE etl.diesel_budget
    ADD CONSTRAINT uk_diesel_budget_row_hash UNIQUE (row_hash);