CREATE TABLE etl.entrada_acero
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha        date                                    NOT NULL,
    recibido_por VARCHAR(150),
    codigo       VARCHAR(100),
    acero        VARCHAR(100),
    nombre_acero VARCHAR(150),
    cantidad     INTEGER,
    row_hash     VARCHAR(64)                             NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_entrada_acero PRIMARY KEY (id)
);

ALTER TABLE etl.entrada_acero
    ADD CONSTRAINT uk_entrada_acero_row_hash UNIQUE (row_hash);

CREATE INDEX ux_entrada_acero_row_hash ON etl.entrada_acero (row_hash);