CREATE TABLE etl.geology_drilling
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha                date                                    NOT NULL,
    bno                  INTEGER,
    empresa              INTEGER,
    maquina              VARCHAR(255),
    fondo_dia_anterior_m DECIMAL(20, 10),
    fondo_actual_m       DECIMAL(20, 10),
    avance_dia_m         DECIMAL(20, 10),
    status               INTEGER,
    estacion             INTEGER,
    jv_holes             VARCHAR(255),
    target               VARCHAR(255),
    target2              VARCHAR(255),
    row_hash             VARCHAR(64)                             NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_geology_drilling PRIMARY KEY (id)
);

ALTER TABLE etl.geology_drilling
    ADD CONSTRAINT uk_geology_drilling_row_hash UNIQUE (row_hash);
CREATE TABLE etl.geology_drilling
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha                date                                    NOT NULL,
    bno                  VARCHAR(255),
    empresa              INTEGER,
    maquina              VARCHAR(255),
    fondo_dia_anterior_m DECIMAL(20, 10),
    fondo_actual_m       DECIMAL(20, 10),
    avance_dia_m         DECIMAL(20, 10),
    status               VARCHAR(255),
    estacion             VARCHAR(255),
    jv_holes             VARCHAR(255),
    target               VARCHAR(255),
    target2              VARCHAR(255),
    row_hash             VARCHAR(64)                             NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_geology_drilling PRIMARY KEY (id)
);

ALTER TABLE etl.geology_drilling
    ADD CONSTRAINT uk_geology_drilling_row_hash UNIQUE (row_hash);
CREATE TABLE etl.geology_drilling
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha                date                                    NOT NULL,
    bno                  VARCHAR(255),
    empresa              VARCHAR(255),
    maquina              VARCHAR(255),
    fondo_dia_anterior_m DECIMAL(20, 10),
    fondo_actual_m       DECIMAL(20, 10),
    avance_dia_m         DECIMAL(20, 10),
    status               VARCHAR(255),
    estacion             VARCHAR(255),
    jv_holes             VARCHAR(255),
    target               VARCHAR(255),
    target2              VARCHAR(255),
    row_hash             VARCHAR(64)                             NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_geology_drilling PRIMARY KEY (id)
);

ALTER TABLE etl.geology_drilling
    ADD CONSTRAINT uk_geology_drilling_row_hash UNIQUE (row_hash);