CREATE TABLE etl.topography
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    row_hash   VARCHAR(64)                             NOT NULL,
    fecha      date                                    NOT NULL,
    lugar_d    VARCHAR(100),
    obra       VARCHAR(100),
    tipo_minado VARCHAR(50),
    zona       VARCHAR(50),
    veta       VARCHAR(50),
    tipo_material VARCHAR(50),
    prioridad  DECIMAL(20, 10),
    lote       VARCHAR(50),
    empresa    VARCHAR(100),
    cuenta     VARCHAR(50),
    grupo      VARCHAR(50),
    area       VARCHAR(50),
    ancho_plan DECIMAL(20, 10),
    alto_plan  DECIMAL(20, 10),
    lad        VARCHAR(50),
    avance     DECIMAL(20, 10),
    disp       DECIMAL(20, 10),
    ancho      DECIMAL(20, 10),
    alto       DECIMAL(20, 10),
    ton        DECIMAL(20, 10),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_topography PRIMARY KEY (id)
);

ALTER TABLE etl.topography
    ADD CONSTRAINT uc_topography_row_hash UNIQUE (row_hash);

CREATE UNIQUE INDEX idx_topography_row_hash ON etl.topography (row_hash);