CREATE TABLE etl.development
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    row_hash      VARCHAR(64)                             NOT NULL,
    fecha         date                                    NOT NULL,
    grupo         VARCHAR(100),
    prioridad     INTEGER,
    lote          VARCHAR(100),
    status        VARCHAR(50),
    mina          VARCHAR(100),
    zona          VARCHAR(100),
    costos        VARCHAR(50),
    elaborado_por VARCHAR(150),
    min_tep       VARCHAR(50),
    obra          VARCHAR(150),
    estructura    VARCHAR(150),
    lugar         VARCHAR(150),
    metros        DECIMAL(20, 10),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_development PRIMARY KEY (id)
);

ALTER TABLE etl.development
    ADD CONSTRAINT uk_dev_row_hash UNIQUE (row_hash);