CREATE TABLE etl.production
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha      date                                    NOT NULL,
    lote       VARCHAR(100),
    mina       VARCHAR(100),
    zona       VARCHAR(100),
    empresa    VARCHAR(150),
    obra       VARCHAR(150),
    estatus    VARCHAR(50),
    estructura VARCHAR(150),
    labor      VARCHAR(150),
    ley_ag     DECIMAL(20, 10),
    ley_au     DECIMAL(20, 10),
    ley_pb     DECIMAL(20, 10),
    ley_zn     DECIMAL(20, 10),
    vpt        DECIMAL(20, 10),
    tipo       VARCHAR(50),
    tons       DECIMAL(20, 10),
    sum_ag     DECIMAL(20, 10),
    sum_au     DECIMAL(20, 10),
    sum_pb     DECIMAL(20, 10),
    sum_zn     DECIMAL(20, 10),
    sum_vpt    DECIMAL(20, 10),
    row_hash   VARCHAR(64)                             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_production PRIMARY KEY (id)
);

ALTER TABLE etl.production
    ADD CONSTRAINT uc_production_row_hash UNIQUE (row_hash);