CREATE TABLE etl.security
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    row_hash   VARCHAR(64)                             NOT NULL,
    fecha      date                                    NOT NULL,
    tipo       VARCHAR(50),
    no         DECIMAL(20, 10),
    comentario VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_security PRIMARY KEY (id)
);

ALTER TABLE etl.security
    ADD CONSTRAINT uc_security_row_hash UNIQUE (row_hash);

CREATE UNIQUE INDEX idx_security_row_hash ON etl.security (row_hash);