package com.pasdm.etl.repository;

import com.pasdm.etl.model.GeologyGrade;
import com.pasdm.etl.model.PlantBudget;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.transaction.annotation.Transactional;

public interface GeologyGradeRepository extends JpaRepository<GeologyGrade, Long> {
    @Modifying
    @Transactional
    @Query(value = """
            INSERT INTO etl.geology_grade (
                  fecha,
                  mina,
                  area,
                  m_minado,
                  mineral,
                  lugar,
                  ml,
                  ancho_planeado,
                  plan,
                  veta,
                  ton_plan2,
                  ton_plan3,
                  concesion,
                  ag_plan,
                  au_plan,
                  pb_plan,
                  zn_plan,
                  ton_pintarron,
                  ton_manteo,
                  ancho_real,
                  ancho_muestreo,
                  ley_ag,
                  ley_au,
                  ley_pb,
                  ley_zn,
                  linea_rez,
                  class,
                  dil_piso,
                  dilucion,
                  ag_dil,
                  au_dil,
                  pb_dil,
                  zn_dil,
                  ag_ton_dil,
                  au_ton_dil,
                  pb_ton_dil,
                  zn_ton_dil,
                  ag_08_dil,
                  au_08_dil,
                  pb_08_dil,
                  zn_08_dil,
                  vpt_tab,
                  vpt_tons,
                  ton_plan_ag,
                  ton_plan_au,
                  ton_plan_pb,
                  ton_plan_zn,
                  vpt_plan,
                  vpt_tons_plan,
                  cumplimiento,
                  cumpli_ley_ag,
                  fc,
                  dif_ag,
                  dif_au,
                  dif_pb,
                  dif_zn,
                  ancho_programado,
                  dilpiso_ton,
                  dil_ton,
                  dil_ancho_min,
                  columna1,
                  min_clave,
                  tipo_minado,
                  clave,
                  obra_veta,
                  m_real,
                  row_hash
              ) VALUES (
                  :#{#geologyGrade.fecha},
                  :#{#geologyGrade.mina},
                  :#{#geologyGrade.area},
                  :#{#geologyGrade.mMinado},
                  :#{#geologyGrade.mineral},
                  :#{#geologyGrade.lugar},
                  :#{#geologyGrade.ml},
                  :#{#geologyGrade.anchoPlaneado},
                  :#{#geologyGrade.plan},
                  :#{#geologyGrade.veta},
                  :#{#geologyGrade.tonPlan2},
                  :#{#geologyGrade.tonPlan3},
                  :#{#geologyGrade.concesion},
                  :#{#geologyGrade.agPlan},
                  :#{#geologyGrade.auPlan},
                  :#{#geologyGrade.pbPlan},
                  :#{#geologyGrade.znPlan},
                  :#{#geologyGrade.tonPintarron},
                  :#{#geologyGrade.tonManteo},
                  :#{#geologyGrade.anchoReal},
                  :#{#geologyGrade.anchoMuestreo},
                  :#{#geologyGrade.leyAg},
                  :#{#geologyGrade.leyAu},
                  :#{#geologyGrade.leyPb},
                  :#{#geologyGrade.leyZn},
                  :#{#geologyGrade.lineaRez},
                  :#{#geologyGrade.clase},
                  :#{#geologyGrade.dilPiso},
                  :#{#geologyGrade.dilucion},
                  :#{#geologyGrade.agDil},
                  :#{#geologyGrade.auDil},
                  :#{#geologyGrade.pbDil},
                  :#{#geologyGrade.znDil},
                  :#{#geologyGrade.agTonDil},
                  :#{#geologyGrade.auTonDil},
                  :#{#geologyGrade.pbTonDil},
                  :#{#geologyGrade.znTonDil},
                  :#{#geologyGrade.ag08Dil},
                  :#{#geologyGrade.au08Dil},
                  :#{#geologyGrade.pb08Dil},
                  :#{#geologyGrade.zn08Dil},
                  :#{#geologyGrade.vptTab},
                  :#{#geologyGrade.vptTons},
                  :#{#geologyGrade.tonPlanAg},
                  :#{#geologyGrade.tonPlanAu},
                  :#{#geologyGrade.tonPlanPb},
                  :#{#geologyGrade.tonPlanZn},
                  :#{#geologyGrade.vptPlan},
                  :#{#geologyGrade.vptTonsPlan},
                  :#{#geologyGrade.cumplimiento},
                  :#{#geologyGrade.cumpliLeyAg},
                  :#{#geologyGrade.fc},
                  :#{#geologyGrade.difAg},
                  :#{#geologyGrade.difAu},
                  :#{#geologyGrade.difPb},
                  :#{#geologyGrade.difZn},
                  :#{#geologyGrade.anchoProgramado},
                  :#{#geologyGrade.dilPisoTon},
                  :#{#geologyGrade.dilTon},
                  :#{#geologyGrade.dilAnchoMin},
                  :#{#geologyGrade.columna1},
                  :#{#geologyGrade.minClave},
                  :#{#geologyGrade.tipoMinado},
                  :#{#geologyGrade.clave},
                  :#{#geologyGrade.obraVeta},
                  :#{#geologyGrade.mReal},
                  :#{#geologyGrade.rowHash}
              )
              ON CONFLICT (row_hash)
              DO UPDATE SET
                  m_minado              = EXCLUDED.m_minado,
                  mineral               = EXCLUDED.mineral,
                  lugar                 = EXCLUDED.lugar,
                  ml                    = EXCLUDED.ml,
                  ancho_planeado        = EXCLUDED.ancho_planeado,
                  plan                  = EXCLUDED.plan,
                  ton_plan2             = EXCLUDED.ton_plan2,
                  ton_plan3             = EXCLUDED.ton_plan3,
                  concesion             = EXCLUDED.concesion,
                  ag_plan               = EXCLUDED.ag_plan,
                  au_plan               = EXCLUDED.au_plan,
                  pb_plan               = EXCLUDED.pb_plan,
                  zn_plan               = EXCLUDED.zn_plan,
                  ton_pintarron         = EXCLUDED.ton_pintarron,
                  ton_manteo            = EXCLUDED.ton_manteo,
                  ancho_real             = EXCLUDED.ancho_real,
                  ancho_muestreo         = EXCLUDED.ancho_muestreo,
                  ley_ag                = EXCLUDED.ley_ag,
                  ley_au                = EXCLUDED.ley_au,
                  ley_pb                = EXCLUDED.ley_pb,
                  ley_zn                = EXCLUDED.ley_zn,
                  linea_rez             = EXCLUDED.linea_rez,
                  class                 = EXCLUDED.class,
                  dil_piso              = EXCLUDED.dil_piso,
                  dilucion              = EXCLUDED.dilucion,
                  ag_dil                = EXCLUDED.ag_dil,
                  au_dil                = EXCLUDED.au_dil,
                  pb_dil                = EXCLUDED.pb_dil,
                  zn_dil                = EXCLUDED.zn_dil,
                  ag_ton_dil            = EXCLUDED.ag_ton_dil,
                  au_ton_dil            = EXCLUDED.au_ton_dil,
                  pb_ton_dil            = EXCLUDED.pb_ton_dil,
                  zn_ton_dil            = EXCLUDED.zn_ton_dil,
                  ag_08_dil             = EXCLUDED.ag_08_dil,
                  au_08_dil             = EXCLUDED.au_08_dil,
                  pb_08_dil             = EXCLUDED.pb_08_dil,
                  zn_08_dil             = EXCLUDED.zn_08_dil,
                  vpt_tab               = EXCLUDED.vpt_tab,
                  vpt_tons              = EXCLUDED.vpt_tons,
                  ton_plan_ag           = EXCLUDED.ton_plan_ag,
                  ton_plan_au           = EXCLUDED.ton_plan_au,
                  ton_plan_pb           = EXCLUDED.ton_plan_pb,
                  ton_plan_zn           = EXCLUDED.ton_plan_zn,
                  vpt_plan              = EXCLUDED.vpt_plan,
                  vpt_tons_plan         = EXCLUDED.vpt_tons_plan,
                  cumplimiento          = EXCLUDED.cumplimiento,
                  cumpli_ley_ag         = EXCLUDED.cumpli_ley_ag,
                  fc                    = EXCLUDED.fc,
                  dif_ag                = EXCLUDED.dif_ag,
                  dif_au                = EXCLUDED.dif_au,
                  dif_pb                = EXCLUDED.dif_pb,
                  dif_zn                = EXCLUDED.dif_zn,
                  ancho_programado      = EXCLUDED.ancho_programado,
                  dilpiso_ton           = EXCLUDED.dilpiso_ton,
                  dil_ton               = EXCLUDED.dil_ton,
                  dil_ancho_min         = EXCLUDED.dil_ancho_min,
                  columna1              = EXCLUDED.columna1,
                  min_clave             = EXCLUDED.min_clave,
                  tipo_minado           = EXCLUDED.tipo_minado,
                  clave                 = EXCLUDED.clave,
                  m_real                = EXCLUDED.m_real,
                  updated_at         = now();
            """, nativeQuery = true)
    void upsert(@Param("geologyGrade") GeologyGrade geologyGrade);
}